---

vagrant_hostname: lamp.local
vagrant_ip: 10.10.10.10
# Virtual machine memory setup.
vm_ram: "2048"

locale: it_IT.UTF-8
language: 'it_IT:it'
timezone: Europe/Rome

# Your local path for all sites.
local_sites_path: "~/Sites"
# Your VM local path for all sites.
vm_sites_path: "/var/www"

# Your site index path.
site_root_path: "/var/www"
db_password: ""

# PHP settings.
php_max_execution_time: "128"
php_memory_limit: "512M"

# Drush.
drush_version: 7.*
