---
- name: Install Python MySQLdb
  apt: name=python-mysqldb state=latest

- name: users | update root password for all hosts
  mysql_user: >
    name=root
    host=localhost
    password={{ db_password }}
    priv=*.*:ALL,GRANT

